version: 2

jobs:
  lint:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: |
          # For isort, must install all "system" dependencies
          pip3 install isort --user
          pip3 install .[all] --user
          pip3 install pytest --user
          isort -rc -c .
      - run: |
          pip3 install black --user
          black --check .
      - run: |
          pip3 install flake8 --user
          flake8 .
  build:
    working_directory: ~/work
    docker:
      - image: circleci/python:3
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y python3-h5py
      - run: pip3 install -U pytest pytest-cov --user
      - checkout
      - run: pip3 install -r test_requirements.txt --user 
      - run: pip3 install . --user
      # The tests
      - run:
          command: pytest --cov pacopy
          working_directory: test/
          env:
            MPLBACKEND: Agg
      # submit to codecov
      - run: apt-get install -y curl
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build
