name: ci

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - uses: actions/checkout@v2
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .
    - name: Lint with black
      run: |
        pip install black
        black --check .

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Install dependencies
      run: |
        sudo apt-get install -y python3-h5py
        pip3 install -r test_requirements.txt
    - name: Install package
      run: |
        pip install .[all]
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest --cov pacopy
    # - name: Submit to codecov
    #   run: bash <(curl -s https://codecov.io/bash)
